/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hashSet_y_TreeSet;

import java.util.Hashtable;
import javax.swing.JOptionPane;

/**
 *
 * @author estudiante
 */
public class AgregarNuevo extends javax.swing.JFrame {

    private Hashtable tablaHash;
    /**
     * Creates new form AgregarNuevo
     */
    public AgregarNuevo(Hashtable tablaHash) {
        initComponents();
        
        this.tablaHash = tablaHash;
        reiniciar();
        setLocationRelativeTo(null);
    }

    public void reiniciar()
    {
        this.jTextField_Cedula.setText("");
        this.jTextField_Nombre.setText("");
        this.jTextField_Nombre.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Cedula = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jTextField_Nombre = new javax.swing.JTextField();
        jTextField_Cedula = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel_Cedula.setText("Cedula");

        jLabel_Nombre.setText("Nombre");

        jTextField_Cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_CedulaKeyPressed(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Nombre)
                            .addComponent(jLabel_Cedula))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Nombre)
                            .addComponent(jTextField_Cedula, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Cedula)
                    .addComponent(jTextField_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nombre)
                    .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(this.jTextField_Cedula.getText().equals("") || this.jTextField_Nombre.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "No deje campos vacios", "", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            tablaHash.put(this.jTextField_Cedula.getText(), new Estudiante(this.jTextField_Cedula.getText(), this.jTextField_Nombre.getText()));
            JOptionPane.showMessageDialog(null, "Se agrego el estudiante.");
            reiniciar();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_CedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CedulaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10)
        {
            String cedula = this.jTextField_Cedula.getText();
        
            if(tablaHash.containsKey(cedula))
            {
                JOptionPane.showMessageDialog(null, "No puede ingresarlo, ya existe en la tabla.", "", JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                this.jTextField_Nombre.setEnabled(true);
                this.jTextField_Nombre.requestFocus();
            }
        }
    }//GEN-LAST:event_jTextField_CedulaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel_Cedula;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JTextField jTextField_Cedula;
    private javax.swing.JTextField jTextField_Nombre;
    // End of variables declaration//GEN-END:variables
}
